### ISSUE TITLE
Q: how to display hierarchical data from xml or json

### ISSUE THREAD

**Issue by jolo2000** [epreston/PSTreeGraph#9]
Hello,

i would like to display some hierarchical data from a xml-file or json-response. 
Now I am looking for some hints or tips how to start with.

Yours Johannes

**Comment by Deepthi-Taduvayi** [comment]
Hi, 

Here is my json content:
```
{
    
    “name": “Example”,
    
    "ID": “01234”,
    
    "accounts": [
                 {
                 
                 "ID": “0”,
                 
                 "name": "Example"
                 
                 }
                 
                 ],
    "children": [
                 {
                 “name”: "Example1”,
                 
                 "ID": “56789”,
                 
                 "accounts": [
                              {
                              "ID": “1”,  
                              "name": "Example1"  
                              
                              }  
                              
                              ],  
                 "children": []  
                 }  
                 ]  
}
```

I have used the same ObjCClassWrapper file to load my Json data into the graph. I have modified the subclasses method like this:
```
 - (NSArray *) subclasses
 {
     // If we haven't built our array of subclasses yet, do so.
     if (subclassesCache == nil) {
         return [NSArray array];
     }
     return subclassesCache;
 }
```

and in PSHTreeGraphViewController.m file, I have modified the below method:

```
-(void) configureNodeView:(UIView *)nodeView
            withModelNode:(id <PSTreeGraphModelNode> )modelNode
{
    NSParameterAssert(nodeView != nil);
    NSParameterAssert(modelNode != nil);

	// NOT FLEXIBLE: treat it like a model node instead of the interface.
	ObjCClassWrapper *objectWrapper = (ObjCClassWrapper *)modelNode;
    objectWrapper.subclasses = self.JSONFromFile.allValues;
	MyLeafView *leafView = (MyLeafView *)nodeView;

	// button
	if ( [objectWrapper childModelNodes].count == 0 ) {
		[leafView.expandButton setHidden:YES];
	}

	// labels
	leafView.titleLabel.text	= objectWrapper.name;
	//leafView.detailLabel.text	= [NSString stringWithFormat:@"%zd bytes",
                                   //objectWrapper.wrappedClassInstanceSize];

}
```

The application did not crash but it didn't load my content. Where am I doing it wrong?

**Comment by epreston** [comment]
I'll take a look when I get back to my desk.

**Comment by Deepthi-Taduvayi** [comment]
Okay. Thank you.

**Comment by skydhax** [comment]
Hi @epreston ,
First of all, I want to thank you , for all this work.
I've been trying to implement the PSTreeGraph with data from a Json File but I'm stuck.
May I provide you a Github repository with my example in order to help me? That would be awesome.
Thanks a lot in advance.

**Comment by lya913** [comment]
HI,  can you give me a demo from  json or plist

**Comment by woshixiaowei** [comment]
HI,  can you give me a demo from  json or plist

**Comment by epreston** [comment]
All the demos currently do this.

On Wed, 3 Apr 2019 at 4:36 pm, liya <notifications@github.com> wrote:

> HI, can you give me a demo from json or plist
>

Ed

**Comment by iFIRTINA** [comment]
Hi,

Do you have an json example used in this application ?

Best Regards.

**Comment by lya913** [comment]
Yes





------------------ Original ------------------
